### ISSUE TITLE
Can't clone

### ISSUE THREAD

**Issue by jallenbradley** [sarmento/kernel-of-truth#1]
I'm getting permissions errors when I try to run 

git clone git@github.com:sarmento/kernal-of-truth 

It could be a permissions problem, but I'm new to git, so I could just be doing this wrong.  

Joe

**Comment by sarmento** [comment]
Do you have a typo there: kernAl ? :)

On Sat, Feb 21, 2015 at 1:21 PM, jallenbradley notifications@github.com
wrote:

> I'm getting permissions errors when I try to run
> 
> git clone git@github.com:sarmento/kernal-of-truth
> 
> It could be a permissions problem, but I'm new to git, so I could just be
> doing this wrong.
> 
> Joe
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sarmento/kernel-of-truth/issues/1.

## 

---

## Luís Sarmento

http://colisor.blogspot.com
http://www.linkedin.com/pub/luis-sarmento/4/4a4/853/

## http://deeprecursion.tumblr.com/

Nota: eu escrevo e-mails seguindo o protocolo http://portuguesglobal.org

**Comment by jallenbradley** [comment]
Hmmm...Please don't tell the universe I only just learned how to spell this word properly.

Weirdly the fix does not seem to help.

git clone git@github.com:sarmento/kernel-of-truth 
Cloning into 'kernel-of-truth'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by jallenbradley** [comment]
I may have some git setup to do.  I'm reading about the configuration now.

**Comment by sarmento** [comment]
I think there is some public/private keys that need to be exchanged there...
I can quite remember what I did when I configured my github two years ago...

On Sat, Feb 21, 2015 at 1:57 PM, jallenbradley notifications@github.com
wrote:

> I may have some git setup to do. I'm reading about the configuration now.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sarmento/kernel-of-truth/issues/1#issuecomment-75395204
> .

## 

---

## Luís Sarmento

http://colisor.blogspot.com
http://www.linkedin.com/pub/luis-sarmento/4/4a4/853/

## http://deeprecursion.tumblr.com/

Nota: eu escrevo e-mails seguindo o protocolo http://portuguesglobal.org

**Comment by jallenbradley** [comment]
Yeah, am just discovering this now.

**Comment by jallenbradley** [comment]
OK, I can clone now! Closing issue.
